### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by matkoniecz** [MTRNord/StreetCompleteFlyer#1]
Consider adding a license

See https://choosealicense.com/ for tl;dr and to confirmation that it is a real problem

Currently no license is mentioned anywhere, what makes this materials fully copyrighted. This is a default for any creative work - what includes software.

Please, please add a license. The fact none is listed makes using this a legal quagmire.

For start - people are not allowed to make pull requests with improvements as it would require distribution of modified materials - that is fully copyrighted.

For example currently it is not legal to use, improve or distribute this contents.
Popular licences include:

 - MIT license that allows people to use code for any purpose
 - GNU GPLv3 that intends to allow everything but to block people from distributing closed source versions that build on open source project

Feel free to ask me questions :) I know and understand that people often prefer to ignore copyright law, unfortunately it will not make it disappear.

**Comment by matkoniecz** [comment]
Additional wrinkle is that some materials are having own license - note bottom right of https://github.com/MTRNord/StreetCompleteFlyer/blob/main/images/banner.png

After thinking a bit: GNU GPLv3 may be a poor solution as it is not really a code.

Maybe CC0 or some other CC license? With separate license for images which have own licences?

**Comment by MTRNord** [comment]
Oops will do this later today. This is obviously not meant to be fully copyrighted/proprietary. 

~~However I wonder if this shouldnt be a creative commons license considering this isn't code 🤔~~ edit just saw your comment and I agree it should probably be a CC license. I will take a look at that later today. 👍

**Comment by matkoniecz** [comment]
I would consider CC0 for text so that reuse will be easier for others (otherwise someone else making leaflet would need to add credit line on it and so on)

**Comment by MTRNord** [comment]
Fixed in 66fc4f4546d9a4d607e11dbdd03ca03b706c07ae Repo is licensed under CC0 and images are licensed under their respective licenses (obviously). So the repo license doesn't apply to the images unless otherwise stated. It does apply to the text/scribus file and the pdf exports.
